-- MySQL Script generated by MySQL Workbench
-- Sun Jun  8 00:24:38 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema belejki
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema belejki
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `belejki` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `belejki` ;

-- -----------------------------------------------------
-- Table `belejki`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `belejki`.`users` (
  `enabled` BIT(1) NULL DEFAULT NULL,
  `is_set_for_deletion` BIT(1) NULL DEFAULT NULL,
  `last_login` DATE NULL DEFAULT NULL,
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `token_expiry` DATETIME(6) NULL DEFAULT NULL,
  `confirmation_token` VARCHAR(255) NULL DEFAULT NULL,
  `first_name` VARCHAR(255) NULL DEFAULT NULL,
  `last_name` VARCHAR(255) NULL DEFAULT NULL,
  `locale` VARCHAR(255) NULL DEFAULT NULL,
  `password` VARCHAR(255) NOT NULL,
  `username` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UKr43af9ap4edm43mmtq01oddj6` (`username` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 68
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `belejki`.`authorities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `belejki`.`authorities` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT NULL DEFAULT NULL,
  `authority` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKk91upmbueyim93v469wj7b2qh` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FKk91upmbueyim93v469wj7b2qh`
    FOREIGN KEY (`user_id`)
    REFERENCES `belejki`.`users` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 70
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `belejki`.`friendships`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `belejki`.`friendships` (
  `friend_id` BIGINT NULL DEFAULT NULL,
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKt0mh1j446gu5rqba17rnknuil` (`friend_id` ASC) VISIBLE,
  INDEX `FK4mcscxflf13uk72aupf6uwbgn` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FK4mcscxflf13uk72aupf6uwbgn`
    FOREIGN KEY (`user_id`)
    REFERENCES `belejki`.`users` (`id`),
  CONSTRAINT `FKt0mh1j446gu5rqba17rnknuil`
    FOREIGN KEY (`friend_id`)
    REFERENCES `belejki`.`users` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `belejki`.`ingredients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `belejki`.`ingredients` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `belejki`.`recipes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `belejki`.`recipes` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT NULL DEFAULT NULL,
  `how_to_make` VARCHAR(4000) NULL DEFAULT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKlc3x6yty3xsupx80hqbj9ayos` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FKlc3x6yty3xsupx80hqbj9ayos`
    FOREIGN KEY (`user_id`)
    REFERENCES `belejki`.`users` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `belejki`.`recipe_ingredients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `belejki`.`recipe_ingredients` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `ingredient_id` BIGINT NULL DEFAULT NULL,
  `recipe_id` BIGINT NULL DEFAULT NULL,
  `quantity` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKgukrw6na9f61kb8djkkuvyxy8` (`ingredient_id` ASC) VISIBLE,
  INDEX `FKcqlw8sor5ut10xsuj3jnttkc` (`recipe_id` ASC) VISIBLE,
  CONSTRAINT `FKcqlw8sor5ut10xsuj3jnttkc`
    FOREIGN KEY (`recipe_id`)
    REFERENCES `belejki`.`recipes` (`id`),
  CONSTRAINT `FKgukrw6na9f61kb8djkkuvyxy8`
    FOREIGN KEY (`ingredient_id`)
    REFERENCES `belejki`.`ingredients` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 17
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `belejki`.`reminders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `belejki`.`reminders` (
  `expiration` DATE NULL DEFAULT NULL,
  `expired` BIT(1) NULL DEFAULT NULL,
  `expires_after_month` BIT(1) NULL DEFAULT NULL,
  `expires_soon` BIT(1) NULL DEFAULT NULL,
  `expires_today` BIT(1) NULL DEFAULT NULL,
  `importance_level` INT NULL DEFAULT NULL,
  `month_mail` BIT(1) NULL DEFAULT NULL,
  `today_mail` BIT(1) NULL DEFAULT NULL,
  `week_mail` BIT(1) NULL DEFAULT NULL,
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT NULL DEFAULT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `reminder_description` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKgibc0ij0e4s7bkldn4xybaanb` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FKgibc0ij0e4s7bkldn4xybaanb`
    FOREIGN KEY (`user_id`)
    REFERENCES `belejki`.`users` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `belejki`.`shop_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `belejki`.`shop_items` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT NULL DEFAULT NULL,
  `color` VARCHAR(255) NULL DEFAULT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKkn962q6vru5cyfybw3hf25bkw` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FKkn962q6vru5cyfybw3hf25bkw`
    FOREIGN KEY (`user_id`)
    REFERENCES `belejki`.`users` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `belejki`.`wishlist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `belejki`.`wishlist` (
  `approximate_price` DOUBLE NULL DEFAULT NULL,
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT NULL DEFAULT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `link` VARCHAR(1024) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKtrd6335blsefl2gxpb8lr0gr7` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FKtrd6335blsefl2gxpb8lr0gr7`
    FOREIGN KEY (`user_id`)
    REFERENCES `belejki`.`users` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 20
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
